### ISSUE TITLE
Sample file for obsidian themes

### ISSUE THREAD

**Issue by rohit04saluja** [obsidianmd/obsidian-sample-theme#3]
Hey

I am trying to develop a new theme and for testing it I was wondering if there is a sample file that exists for testing out all the theming styles

It would be great if it can be included in this repo.

**Comment by lishid** [comment]
I'm not sure I understand what you're looking for. I invite you to join our discord server or our forum to ask. Hopefully someone can help you find what you need.

https://obsidian.md/community
