### ISSUE TITLE
Why isn't there a restricted mode for themes?

### ISSUE THREAD

**Issue by alberfantom** [obsidianmd/obsidian-sample-theme#5]
![Screenshot_20241109-111911.jpg](https://github.com/user-attachments/assets/b8c22967-4db9-4318-b2ab-06dfc1def9ad)

![Screenshot_20241109-111923.jpg](https://github.com/user-attachments/assets/d69213e4-e3d3-4302-a893-07500faa7b04)

**Comment by lishid** [comment]
This is not the right place for questions. Please go to https://forum.obsidian.md/ instead.
